# Generated by Django 3.1.1 on 2020-09-01 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaounceApp', '0003_image_imagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageFile',
        ),
    ]
